### ISSUE TITLE
Verify if model weights file exists before running prediction

### ISSUE THREAD

**Issue by chrstn-hntschl** [chrstn-hntschl/deepvcd#18]
If weights file given to `models.alexnet.AlexNet.py`does not exist, an error is thrown only during prediction. Check if file exists already at beginning or at least catch error during loading of weights file to give a proper error message.

**Comment by chrstn-hntschl** [comment]
The current error thrown:
`Using weights from '/data/checkpoints/ILSVRC2012/normalization_lrm/seed59498/AlexNetFlat_lrn.h5'
Traceback (most recent call last):
  File "deepvcd/models/alexnet/AlexNet.py", line 432, in <module>
    _main(args)
  File "deepvcd/models/alexnet/AlexNet.py", line 368, in _main
    gt, scores_ = predict(norm=None if cli_args.norm.lower()=="none" else cli_args.norm,
  File "deepvcd/models/alexnet/AlexNet.py", line 313, in predict
    model = model_class(include_top=True, input_shape=(input_size, input_size, 3), norm=norm, weights=weights, classes=num_classes)
  File "deepvcd/models/alexnet/AlexNet.py", line 126, in AlexNetFlat
    raise ValueError('The `weights` argument should be either '
ValueError: The `weights` argument should be either `None` (random initialization), `imagenet` (pre-training on ImageNet) or pointing to a local hdf5 weights file.
make: *** [Makefile:55: test_alexnet] Error 1
`
